apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ai-customer-service
  region: us-east-1

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    labels:
      role: worker