# Main Application Service
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: LoadBalancer    # Makes service externally accessible
  ports:
  - port: 80           # External port
    targetPort: 8000   # Container port
  selector:
    app: ai-customer-service
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP      # Internal access only
  ports:
  - port: 6379        # Service port
    targetPort: 6379  # Container port
  selector:
    app: redis